### ISSUE TITLE
Time slot for morning does not expand

### ISSUE THREAD

**Issue by mpally** [mt-support/tribe-ext-schedule-day-view#4]
Hi,
All events in the other time slots get expandet, when acrive. But not those in the morning. 
Do you have any idea, what goes wrong?
Thanks a lot and regards
Martin

**Comment by cliffordp** [comment]
Thanks for reporting the issue, but please direct this to https://support.theeventscalendar.com/ instead so we can follow our procedures and protocols for testing/fixing this.
